# Generated by Django 4.2.8 on 2024-01-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=15),
        ),
    ]
