# Generated by Django 4.2.8 on 2024-01-26 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapp", "0002_alter_city_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
    ]
