# Generated by Django 4.2.8 on 2024-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapp", "0005_rename_custuser_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="my_city",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
